In [1]:
import pandas as pd
import numpy as np
#library untuk mrmr
from sklearn.feature_selection import f_regression
from sklearn.model_selection  import train_test_split
#svm + bootstrap
from sklearn.utils import resample
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV #tuning param
from sklearn.metrics import classification_report, confusion_matrix  
#plotting
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os
import glob

In [26]:
fitur = pd.DataFrame([])  #membuat dataframe 
i=1
for i in range(11): #looping 
  i=i+1
  FILE_PATH = '/content/drive/MyDrive/csv fitur/subband baru/'+str(i)+'.csv' #path file csv dalam satu folder, pakai looping for i in range agar bacanya urut 
  data = pd.read_csv(FILE_PATH, sep=",", header=0) #read csv, berdasarkan path, row 0 sbg header 
  
  fitur = pd.concat([fitur,data],axis=0) #concatenate csv cs jadi satu data frame 'all_data'


In [27]:
pd_data=pd.DataFrame(fitur)
print(pd_data)

      class         f1         f2  ...       f30        f31        f32
0         1  88.276858  33.142509  ...  0.309109  27.097155  20.713684
1         1  65.298956  24.897021  ... -0.611335  21.081516  15.450969
2         1  78.681862  20.279236  ... -0.933912  23.224617  17.313553
3         1  49.117960  17.697399  ...  0.995559  15.165962  12.141533
4         1  50.639018  21.073946  ...  1.086484  15.909132  12.408689
...     ...        ...        ...  ...       ...        ...        ...
2751      1  39.458458  17.707671  ...  1.447036  13.858376  10.298096
2752      1  47.421796  21.564318  ...  0.727066  17.272902  12.008964
2753      1  44.787647  18.344150  ... -0.201333  14.601041   9.467959
2754      1  19.300815  10.975899  ...  0.270798   8.410209   6.680703
2755      1  41.886231  19.494902  ...  0.354108  13.360366   8.679322

[30430 rows x 33 columns]


In [5]:
target=pd_data.iloc[:,0]
y=pd.Series(target)
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
2751    1
2752    1
2753    1
2754    1
2755    1
Name: class, Length: 30430, dtype: int64


In [6]:
fitur = pd_data.drop("class", axis=1)
X=pd.DataFrame(fitur)

In [7]:
print(X)

             f1         f2         f3  ...       f30        f31        f32
0     88.276858  33.142509  22.795904  ...  0.309109  27.097155  20.713684
1     65.298956  24.897021  18.887724  ... -0.611335  21.081516  15.450969
2     78.681862  20.279236  15.321478  ... -0.933912  23.224617  17.313553
3     49.117960  17.697399  14.996819  ...  0.995559  15.165962  12.141533
4     50.639018  21.073946  20.665048  ...  1.086484  15.909132  12.408689
...         ...        ...        ...  ...       ...        ...        ...
2751  39.458458  17.707671  13.019914  ...  1.447036  13.858376  10.298096
2752  47.421796  21.564318  16.027540  ...  0.727066  17.272902  12.008964
2753  44.787647  18.344150  10.480548  ... -0.201333  14.601041   9.467959
2754  19.300815  10.975899   9.787902  ...  0.270798   8.410209   6.680703
2755  41.886231  19.494902  11.862668  ...  0.354108  13.360366   8.679322

[30430 rows x 32 columns]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #split data 80:20

In [9]:
F=pd.Series(f_regression(X_train,y_train)[0],index=X_train.columns) #menghitung f regression 
corr=X_train.corr().abs().clip(.00001) #menghitung korelasi, .clip biar ga divide by 0 

#buat list selected dan ga 
selected=[]
not_selected=list(X_train.columns)

for i in range(15):
  score=F.loc[not_selected]/corr.loc[not_selected,selected].mean(axis=1).fillna(.00001) #FCQ = F/corr
  print(score) #print score mrmr
  best=score.index[score.argmax()] #memilih yg paling tinggi 
  selected.append(best) #dimasukian ke list selected + digabung 
  not_selected.remove(best) #menghilangkan fitur yg sudah terpilih
  

f1     6.136723e+07
f2     1.436409e+08
f3     1.461700e+08
f4     2.655801e+08
f5     1.484192e+08
f6     3.739829e+08
f7     1.352890e+08
f8     4.291554e+07
f9     7.874706e+07
f10    1.153059e+08
f11    3.196899e+08
f12    1.890973e+08
f13    4.193229e+08
f14    6.129375e+07
f15    1.435783e+08
f16    1.462071e+08
f17    2.654237e+08
f18    1.485314e+08
f19    3.740009e+08
f20    1.545259e+06
f21    1.499455e+07
f22    1.219785e+09
f23    2.917308e+08
f24    3.887964e+09
f25             NaN
f26    1.138944e+08
f27    3.208549e+04
f28    2.802786e+08
f29    2.443175e+08
f30    8.657343e+07
f31    1.027289e+08
f32    6.555492e+07
dtype: float64
f1      3081.126746
f2      5539.725896
f3      4921.210476
f4      6487.655555
f5      4270.991602
f6      6993.838873
f7      4619.426498
f8      2414.195193
f9      3509.873727
f10     4128.279334
f11     6859.061580
f12     4875.291119
f13     7545.733931
f14     3080.086963
f15     5537.480935
f16     4921.746491
f17     6484.836096
f18  

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:284: RuntimeWarning: invalid value encountered in sqrt
  X_norms = np.sqrt(row_norms(X.T, squared=True) - n_samples * X_means ** 2)


In [10]:
print(selected)

['f24', 'f22', 'f23', 'f13', 'f19', 'f26', 'f6', 'f30', 'f28', 'f11', 'f29', 'f4', 'f17', 'f12', 'f2']


In [11]:
print(not_selected)

['f1', 'f3', 'f5', 'f7', 'f8', 'f9', 'f10', 'f14', 'f15', 'f16', 'f18', 'f20', 'f21', 'f25', 'f27', 'f31', 'f32']


In [53]:
#fitur diskriminan
 
n_iterations = 10  #No. of bootstrap samples to be repeated (created)
n_size = int(len(pd_data) * 0.80)
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}

In [54]:
print(n_size)

24344


In [56]:
len(pd_data)

30430

In [28]:
dat=pd_data.drop(['f1', 'f3', 'f5', 'f7', 'f8', 'f9', 'f10', 'f14', 'f15', 'f16', 'f18', 'f20', 'f21', 'f25', 'f27', 'f31', 'f32'],axis=1)

In [29]:
values=dat.values
print(values)

[[   1.           33.14250943   13.44297013 ...   94.92737735
  -106.83513534    0.30910916]
 [   1.           24.89702114   11.77010735 ...   95.31371589
   -97.57478855   -0.61133542]
 [   1.           20.2792356    10.99746327 ...  101.55481426
   -79.31230595   -0.93391191]
 ...
 [   1.           18.34415037    8.74073947 ...  121.23055481
  -112.66718137   -0.20133287]
 [   1.           10.97589886    7.57826004 ...   29.68225815
   -36.25720419    0.27079808]
 [   1.           19.49490164    8.38855956 ...  117.56437694
   -75.90161057    0.35410806]]


In [ ]:
#tuning parameter
svc = SVC(kernel='rbf',decision_function_shape='ovo')
grid = GridSearchCV(svc, param_grid,refit = True, verbose = 3)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total= 1.4min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  1.4min remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total= 1.4min
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  2.8min remaining:    0.0s


[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total= 1.4min
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total= 1.4min
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total= 1.4min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.791, total= 1.0min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.794, total= 1.0min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.790, total= 1.1min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.791, total= 1.2min
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed: 90.2min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovo', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [ ]:
print(grid.best_params_)
print(grid.score(X_test,y_test))

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
0.9457771935589878


In [ ]:
print(values[:,1:])

In [ ]:
print(values[:,:-1])

In [ ]:
print(values[:,-1])

In [57]:
#https://www.kaggle.com/sasha18/resampling-methods-using-bootstrap-cv
stats = list()
for i in range(n_iterations):

    #prepare train & test sets
    train = resample(values, n_samples = n_size) #Sampling with replacement..whichever is not used in training data will be used in test data
    test = np.array([x for x in values if x.tolist() not in train.tolist()]) #np.array([x for x in values if x not in train]) #picking rest of the data not considered in training sample
    
    #fit model
    model = SVC(kernel='rbf',decision_function_shape='ovo',C=1000,gamma=0.0001)
    model.fit(train[:,1:], train[:,0]) #model.fit(X_train,y_train) i.e model.fit(train set, train label as it is a classifier)
    
    #evaluate model
    predictions = model.predict(test[:,1:]) #model.predict(X_test)
    score = accuracy_score(test[:,0], predictions) #accuracy_score(y_test, y_pred)
    #caution, overall accuracy score can mislead when classes are imbalanced
    
    print(score)
    stats.append(score)

0.9462287458218283
0.9436681542175727
0.9461588969139856
0.9461165761268536
0.943403133694538
0.9420619767954178
0.9440117560617193
0.9428004993024451
0.9457569735776845
0.9428384184082138


In [59]:
accuracy=np.array(stats)
print('average: ', accuracy.mean()*100)

average:  94.4304513092026


In [60]:
cnfmatrix=confusion_matrix(test[:,0],  predictions)
print(cnfmatrix)

[[9619  162   13]
 [ 188 2835  100]
 [  96  226  494]]


In [61]:
 print(classification_report(test[:,0],predictions))

              precision    recall  f1-score   support

         1.0       0.97      0.98      0.98      9794
         2.0       0.88      0.91      0.89      3123
         3.0       0.81      0.61      0.69       816

    accuracy                           0.94     13733
   macro avg       0.89      0.83      0.85     13733
weighted avg       0.94      0.94      0.94     13733



In [68]:
cnfmatrix=confusion_matrix(test[:,0],  predictions)
print(cnfmatrix)

[[9619  162   13]
 [ 188 2835  100]
 [  96  226  494]]


In [70]:
n_classes=3
for c in range(n_classes):
    tp = cnfmatrix[c,c]
    fp = sum(cnfmatrix[:,c]) - cnfmatrix[c,c]
    fn = sum(cnfmatrix[c,:]) - cnfmatrix[c,c]
    tn = sum(np.delete(sum(cnfmatrix)-cnfmatrix[c,:],c))

    sensivity = tp/(tp+fn)
    specificity = tn/(tn+fp) 

    print("for class {}: sensivity {}, specificity {}, tp {}, fp {},fn {},tn {}".format(c,round(sensivity,4), round(specificity,4),round(tp),round(fp),round(fn),round(tn)))

for class 0: sensivity 0.98, specificity 0.93, tp 9619, fp 284,fn 175,tn 3655
for class 1: sensivity 0.91, specificity 0.96, tp 2835, fp 388,fn 288,tn 10222
for class 2: sensivity 0.61, specificity 0.99, tp 494, fp 113,fn 322,tn 12804


In [ ]:
sum(cnfmatrix)

In [69]:
#fn = sum(cnfmatrix[c,:]) - cnfmatrix[c,c]
cnfmatrix[2,:]

array([ 96, 226, 494])

In [ ]:
sum(cnfmatrix)-cnfmatrix[2,:]

array([4347, 1313,   59])

In [ ]:
np.delete(sum(cnfmatrix)-cnfmatrix[2,:],2)

array([4347, 1313])

In [ ]:
sum(cnfmatrix[2,:]) - cnfmatrix[2,2]

117